### ISSUE TITLE
Stroke dash length and space between dashes do not match other platforms

### ISSUE THREAD

**Issue by marlenecota** [marlenecota/react-native-svg#14]
``` JSX
<Svg width="200" height="60">
  <Rect
    x="5%"
    y="5%"
    width="90%"
    height="90%"
    fill="rgb(0,0,255)"
    strokeWidth="3"
    stroke="rgb(0,0,0)"
    strokeDasharray="5,10"
  />
</Svg>
```

Expected:
![image](https://user-images.githubusercontent.com/1422161/113491774-fc572f00-9487-11eb-8d3d-e0a2160e9588.png)

Actual:
![image](https://user-images.githubusercontent.com/1422161/113491789-1bee5780-9488-11eb-9601-d5b870e3ba21.png)

**Comment by agniuks** [comment]
Closing, fixed by #16 & remaining work tracked with #17 😊
