### ISSUE TITLE
Stroke dashArray does not match other platforms

### ISSUE THREAD

**Issue by agniuks** [marlenecota/react-native-svg#17]
```JSX
<Svg height="80" width="225">
      <G fill="none" stroke="black" strokeWidth="4">
      <Path strokeDasharray="5,5" d="M5 20 l215 0" />
      <Path strokeDasharray="10,10" d="M5 40 l215 0" />
      <Path strokeDasharray="20,10,5,5,5,10" d="M5 60 l215 0" />
      </G>
</Svg>
```

Expected:
![image](https://user-images.githubusercontent.com/41223743/113624595-74a72700-9625-11eb-9a98-f19c72097243.png)

Actual:
![image](https://user-images.githubusercontent.com/41223743/113625755-f3e92a80-9626-11eb-93e8-05d0852da2ea.png)

**Comment by marlenecota** [comment]
Looks like Web and iOS have different behavior from Android... and we match Android. We can't match both, so closing the bug. 
![image](https://user-images.githubusercontent.com/1422161/113815088-7bb65e00-9727-11eb-8c45-302791c0a66f.png)
